kind = "web"
previewPath = "/"
title = "Hospital Management System"
version = "1.0.0"
id = "artifacts/hms"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22938

[services.development]
run = "pnpm --filter @workspace/hms run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hms", "run", "build" ]
serve = "static"
publicDir = "artifacts/hms/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22938"
BASE_PATH = "/"
